'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Class Reportes

    Protected WithEvents pnlAlerta As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblAlerta As Global.System.Web.UI.WebControls.Label
    Protected WithEvents pnlParamEmpleado As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents ddlEmpleado As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents pnlParamDepto As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents ddlDepto As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents pnlParamFecha As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents ddlMes As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents txtAnio As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents pnlParamDias As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents txtDias As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents hfReporte As Global.System.Web.UI.WebControls.HiddenField
    Protected WithEvents btnEjecutar As Global.System.Web.UI.WebControls.Button
    Protected WithEvents pnlResultado As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblTituloResultado As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblTotalRegistros As Global.System.Web.UI.WebControls.Label
    Protected WithEvents gvResultado As Global.System.Web.UI.WebControls.GridView

End Class
