'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Class Viaticos

    Protected WithEvents pnlAlerta As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblAlerta As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblPendientes As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblAprobados As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblLiquidados As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblRechazados As Global.System.Web.UI.WebControls.Label
    Protected WithEvents ddlEmpleadoFiltro As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents ddlEstadoFiltro As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents btnFiltrar As Global.System.Web.UI.WebControls.Button
    Protected WithEvents gvViaticos As Global.System.Web.UI.WebControls.GridView
    Protected WithEvents ddlEmpleado As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents txtDestino As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtFechaSalida As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtFechaRetorno As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtMonto As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents ddlAprobadoPor As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents btnGuardarViatico As Global.System.Web.UI.WebControls.Button
    Protected WithEvents hfIdViatico As Global.System.Web.UI.WebControls.HiddenField
    Protected WithEvents txtMontoGastado As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents btnConfirmarLiquidar As Global.System.Web.UI.WebControls.Button

End Class
