'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Class Licencias

    Protected WithEvents pnlAlerta As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblAlerta As Global.System.Web.UI.WebControls.Label
    Protected WithEvents ddlEmpleadoFiltro As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents ddlEstadoFiltro As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents btnFiltrar As Global.System.Web.UI.WebControls.Button
    Protected WithEvents gvLicencias As Global.System.Web.UI.WebControls.GridView
    Protected WithEvents gvPorVencer As Global.System.Web.UI.WebControls.GridView
    Protected WithEvents lblContPorVencer As Global.System.Web.UI.WebControls.Label
    Protected WithEvents ddlEmpleado As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents ddlTipoLic As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents txtNumero As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtOrganismo As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtFechaEmision As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtFechaVenc As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtHabilitaciones As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents btnGuardarLicencia As Global.System.Web.UI.WebControls.Button
    Protected WithEvents hfIdLicencia As Global.System.Web.UI.WebControls.HiddenField
    Protected WithEvents txtNuevaFechaVenc As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtHabRenovar As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents btnConfirmarRenovar As Global.System.Web.UI.WebControls.Button

End Class
